services:
  - type: static
    name: demarche-francaise
    buildCommand: npm install && npm run build
    publishDir: dist
    staticPublishPath: /
    headers:
      /**:
        - key: Cache-Control
          value: no-store
    spa: true