services:
  - type: web
    name: demarche-francaise
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html